modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Akrivus/RESTfulCraft/issues"

[[mods]]
modId="restfulcraft"
version="${file.jarVersion}"
displayName="RESTfulCraft"
displayURL="https://github.com/Akrivus/RESTfulCraft"
logoFile="assets.restfulcraft.logo.png"
credits="Designed and engineered by Owen Adrian. Powered by Spark Framework."
authors="Owen Adrian"
description='''
Introducing software development concepts to Minecraft by turning worlds into a RESTful web service that allows players to create, view, update, and destroy blocks with code or tools such as Postman or cURL.
'''
[[dependencies.restfulcraft]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.restfulcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
